name: Firebase Hosting
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.19.6
      - run: flutter pub get
      - run: dart pub global activate flutterfire_cli
      - run: flutter build web --release --web-renderer canvaskit
      - uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEVESSENTIALS_D2968 }}
          channelId: live
          projectId: devessentials-d2968
