name: Flutter macOS Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter build macos --release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/macos/Build/Products/Release/*.app"
          tag: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
